// Code generated by protoc-gen-go-kit-grpc.

package test

import (
	"context"
	kitlog "github.com/go-kit/log"
	"log"
	"os"
	"testing"
)

func TestWallet_Insert(t *testing.T) {

	var logger kitlog.Logger
	logger = kitlog.NewJSONLogger(os.Stdout)
	logger = kitlog.With(logger, "ts", kitlog.DefaultTimestampUTC)
	logger = kitlog.With(logger, "caller", kitlog.DefaultCaller)

	client := NewWalletClientImpl(logger)
	rsp, err := client.Insert(context.TODO(), &InsertRequest{
		Item: &Item{
			UserId: new(string),
			Id:     "string",
			Val:    new(TestEnum),
			Val2:   TestEnum_UNIVERSAL,
		},
	})
	if err != nil {
		t.Error(err)
		return
	}
	log.Printf("rsp: %v", rsp)
}
func TestWallet_Delete(t *testing.T) {

	var logger kitlog.Logger
	logger = kitlog.NewJSONLogger(os.Stdout)
	logger = kitlog.With(logger, "ts", kitlog.DefaultTimestampUTC)
	logger = kitlog.With(logger, "caller", kitlog.DefaultCaller)

	client := NewWalletClientImpl(logger)
	rsp, err := client.Delete(context.TODO(), &DeleteRequest{
		Id:     []string{},
		Corpus: DeleteRequest_UNIVERSAL,
	})
	if err != nil {
		t.Error(err)
		return
	}
	log.Printf("rsp: %v", rsp)
}
