// Code generated by protoc-gen-go-ascii. DO NOT EDIT.

package test

import (
	"context"
	"github.com/coolrc136/go-kit-micro/sd"
	"github.com/go-kit/kit/endpoint"
	"github.com/go-kit/log"
	"google.golang.org/grpc"
)

type ClientImpl struct {
	insert endpoint.Endpoint
	delete endpoint.Endpoint
}

func NewWalletClientImpl(name string, logger log.Logger) *ClientImpl {
	instancer, err := sd.NewInstancer(name, logger)
	if err != nil {
		panic(err)
	}

	return &ClientImpl{

		insert: sd.GetEndPoint(instancer, func(conn *grpc.ClientConn, ctx context.Context, request interface{}) (interface{}, error) {
			client := NewWalletClient(conn)
			req := request.(*InsertRequest)

			return client.Insert(ctx, req)
		}, logger),
		delete: sd.GetEndPoint(instancer, func(conn *grpc.ClientConn, ctx context.Context, request interface{}) (interface{}, error) {
			client := NewWalletClient(conn)
			req := request.(*DeleteRequest)

			return client.Delete(ctx, req)
		}, logger),
	}
}

// Insert
// insert 234124321
// adasda
// frtgrt
// asdad
func (n *ClientImpl) Insert(ctx context.Context, req *InsertRequest) (*InsertResponse, error) {
	rsp, err := n.insert(ctx, req)
	if err != nil {
		return nil, err
	}
	res := rsp.(*InsertResponse)
	return res, err
}

// Delete
func (n *ClientImpl) Delete(ctx context.Context, req *DeleteRequest) (*DeleteResponse, error) {
	rsp, err := n.delete(ctx, req)
	if err != nil {
		return nil, err
	}
	res := rsp.(*DeleteResponse)
	return res, err
}
